### ISSUE TITLE
Support _netrc files for windows

### ISSUE THREAD

**Issue by jurkov** [gribouille/netrc#1]
It is quite strange but on Windows the `.netrc` file has the name `_netrc`.
Please add `_netrc` support.

Sources:
https://stackoverflow.com/questions/6031214/git-how-to-use-netrc-file-on-windows-to-save-user-and-password
https://www.labkey.org/Documentation/wiki-page.view?name=netrc
https://github.com/curl/curl/blob/6e4b7abfd3bef38130598b7f62289881f448a13c/docs/cmdline-opts/netrc.md?plain=1#L28

**Comment by gribouille** [comment]
Ok, `_netrc` replaces `.netrc` on Windows or it's an alternative ?

**Comment by T-256** [comment]
Curl:
> On Windows two filenames in the home directory are checked: *.netrc* and *_netrc*, preferring the former.

Select each one will be correct. when both available, `_netrc` preferred.
