### ISSUE TITLE
Unable to find .netrc file when $HOME is undefined on linux

### ISSUE THREAD

**Issue by chrisirhc** [gribouille/netrc#4]
Encountered this via https://github.com/astral-sh/uv/issues/3471#issuecomment-2274569743 .
I was surprised to find that uv was unable to find .netrc file whereas pip could, with the same environment setup.

Seems like there's some special handling in pip to find .netrc where this library wasn't able to:
https://github.com/pypa/pip/blob/e98cc5ce078d8c8afd6804ff4e61aa2b12d05715/src/pip/_vendor/requests/utils.py#L206-L233

**Comment by gribouille** [comment]
Indeed, pip use `~` and not `$HOME`. We can add `~` in fallback.
